// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models/average.proto

package average

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Average struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Average) Reset()         { *m = Average{} }
func (m *Average) String() string { return proto.CompactTextString(m) }
func (*Average) ProtoMessage()    {}
func (*Average) Descriptor() ([]byte, []int) {
	return fileDescriptor_2abb0f1a4fa395b0, []int{0}
}

func (m *Average) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Average.Unmarshal(m, b)
}
func (m *Average) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Average.Marshal(b, m, deterministic)
}
func (m *Average) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Average.Merge(m, src)
}
func (m *Average) XXX_Size() int {
	return xxx_messageInfo_Average.Size(m)
}
func (m *Average) XXX_DiscardUnknown() {
	xxx_messageInfo_Average.DiscardUnknown(m)
}

var xxx_messageInfo_Average proto.InternalMessageInfo

func (m *Average) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type AverageRequest struct {
	Average              *Average `protobuf:"bytes,1,opt,name=average,proto3" json:"average,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AverageRequest) Reset()         { *m = AverageRequest{} }
func (m *AverageRequest) String() string { return proto.CompactTextString(m) }
func (*AverageRequest) ProtoMessage()    {}
func (*AverageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2abb0f1a4fa395b0, []int{1}
}

func (m *AverageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AverageRequest.Unmarshal(m, b)
}
func (m *AverageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AverageRequest.Marshal(b, m, deterministic)
}
func (m *AverageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AverageRequest.Merge(m, src)
}
func (m *AverageRequest) XXX_Size() int {
	return xxx_messageInfo_AverageRequest.Size(m)
}
func (m *AverageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AverageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AverageRequest proto.InternalMessageInfo

func (m *AverageRequest) GetAverage() *Average {
	if m != nil {
		return m.Average
	}
	return nil
}

type AverageResponse struct {
	Result               float32  `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AverageResponse) Reset()         { *m = AverageResponse{} }
func (m *AverageResponse) String() string { return proto.CompactTextString(m) }
func (*AverageResponse) ProtoMessage()    {}
func (*AverageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2abb0f1a4fa395b0, []int{2}
}

func (m *AverageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AverageResponse.Unmarshal(m, b)
}
func (m *AverageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AverageResponse.Marshal(b, m, deterministic)
}
func (m *AverageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AverageResponse.Merge(m, src)
}
func (m *AverageResponse) XXX_Size() int {
	return xxx_messageInfo_AverageResponse.Size(m)
}
func (m *AverageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AverageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AverageResponse proto.InternalMessageInfo

func (m *AverageResponse) GetResult() float32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Average)(nil), "average.Average")
	proto.RegisterType((*AverageRequest)(nil), "average.AverageRequest")
	proto.RegisterType((*AverageResponse)(nil), "average.AverageResponse")
}

func init() { proto.RegisterFile("models/average.proto", fileDescriptor_2abb0f1a4fa395b0) }

var fileDescriptor_2abb0f1a4fa395b0 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc9, 0xcd, 0x4f, 0x49,
	0xcd, 0x29, 0xd6, 0x4f, 0x2c, 0x4b, 0x2d, 0x4a, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x87, 0x72, 0x95, 0x14, 0xb9, 0xd8, 0x1d, 0x21, 0x4c, 0x21, 0x31, 0x2e, 0xb6, 0xbc,
	0xd2, 0xdc, 0xa4, 0xd4, 0x22, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x28, 0x4f, 0xc9, 0x86,
	0x8b, 0x0f, 0xaa, 0x24, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x8b, 0x0b, 0xa6, 0x1f,
	0xac, 0x94, 0xdb, 0x48, 0x40, 0x0f, 0x66, 0x3c, 0x4c, 0x25, 0xdc, 0x02, 0x4d, 0x2e, 0x7e, 0xb8,
	0xee, 0xe2, 0x82, 0xfc, 0xbc, 0x62, 0xb0, 0x45, 0x45, 0xa9, 0xc5, 0xa5, 0x39, 0x25, 0x60, 0xdd,
	0x4c, 0x41, 0x50, 0x9e, 0x51, 0x02, 0x97, 0xa8, 0x73, 0x7e, 0x6e, 0x41, 0x69, 0x49, 0x2a, 0x54,
	0x47, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x3b, 0x17, 0x1f, 0xaa, 0x84, 0x90, 0x38,
	0x86, 0x85, 0x10, 0xa7, 0x49, 0x49, 0x60, 0x4a, 0x40, 0x6c, 0x55, 0x62, 0xd0, 0x60, 0x74, 0xe2,
	0x8c, 0x82, 0xb9, 0x2b, 0x89, 0x0d, 0x1c, 0x10, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9e,
	0x01, 0xaa, 0x51, 0x20, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ComputeAverageServiceClient is the client API for ComputeAverageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ComputeAverageServiceClient interface {
	ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (ComputeAverageService_ComputeAverageClient, error)
}

type computeAverageServiceClient struct {
	cc *grpc.ClientConn
}

func NewComputeAverageServiceClient(cc *grpc.ClientConn) ComputeAverageServiceClient {
	return &computeAverageServiceClient{cc}
}

func (c *computeAverageServiceClient) ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (ComputeAverageService_ComputeAverageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ComputeAverageService_serviceDesc.Streams[0], "/average.ComputeAverageService/ComputeAverage", opts...)
	if err != nil {
		return nil, err
	}
	x := &computeAverageServiceComputeAverageClient{stream}
	return x, nil
}

type ComputeAverageService_ComputeAverageClient interface {
	Send(*AverageRequest) error
	CloseAndRecv() (*AverageResponse, error)
	grpc.ClientStream
}

type computeAverageServiceComputeAverageClient struct {
	grpc.ClientStream
}

func (x *computeAverageServiceComputeAverageClient) Send(m *AverageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *computeAverageServiceComputeAverageClient) CloseAndRecv() (*AverageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AverageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ComputeAverageServiceServer is the server API for ComputeAverageService service.
type ComputeAverageServiceServer interface {
	ComputeAverage(ComputeAverageService_ComputeAverageServer) error
}

// UnimplementedComputeAverageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedComputeAverageServiceServer struct {
}

func (*UnimplementedComputeAverageServiceServer) ComputeAverage(srv ComputeAverageService_ComputeAverageServer) error {
	return status.Errorf(codes.Unimplemented, "method ComputeAverage not implemented")
}

func RegisterComputeAverageServiceServer(s *grpc.Server, srv ComputeAverageServiceServer) {
	s.RegisterService(&_ComputeAverageService_serviceDesc, srv)
}

func _ComputeAverageService_ComputeAverage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputeAverageServiceServer).ComputeAverage(&computeAverageServiceComputeAverageServer{stream})
}

type ComputeAverageService_ComputeAverageServer interface {
	SendAndClose(*AverageResponse) error
	Recv() (*AverageRequest, error)
	grpc.ServerStream
}

type computeAverageServiceComputeAverageServer struct {
	grpc.ServerStream
}

func (x *computeAverageServiceComputeAverageServer) SendAndClose(m *AverageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *computeAverageServiceComputeAverageServer) Recv() (*AverageRequest, error) {
	m := new(AverageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ComputeAverageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "average.ComputeAverageService",
	HandlerType: (*ComputeAverageServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ComputeAverage",
			Handler:       _ComputeAverageService_ComputeAverage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "models/average.proto",
}
