// Code generated by protoc-gen-go. DO NOT EDIT.
// source: go-grpc-find-maximum/models/maximum.proto

package maximum

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Number struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Number) Reset()         { *m = Number{} }
func (m *Number) String() string { return proto.CompactTextString(m) }
func (*Number) ProtoMessage()    {}
func (*Number) Descriptor() ([]byte, []int) {
	return fileDescriptor_d531410882a4b8ff, []int{0}
}

func (m *Number) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Number.Unmarshal(m, b)
}
func (m *Number) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Number.Marshal(b, m, deterministic)
}
func (m *Number) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Number.Merge(m, src)
}
func (m *Number) XXX_Size() int {
	return xxx_messageInfo_Number.Size(m)
}
func (m *Number) XXX_DiscardUnknown() {
	xxx_messageInfo_Number.DiscardUnknown(m)
}

var xxx_messageInfo_Number proto.InternalMessageInfo

func (m *Number) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type MaximumRequest struct {
	Number               *Number  `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaximumRequest) Reset()         { *m = MaximumRequest{} }
func (m *MaximumRequest) String() string { return proto.CompactTextString(m) }
func (*MaximumRequest) ProtoMessage()    {}
func (*MaximumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d531410882a4b8ff, []int{1}
}

func (m *MaximumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaximumRequest.Unmarshal(m, b)
}
func (m *MaximumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaximumRequest.Marshal(b, m, deterministic)
}
func (m *MaximumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaximumRequest.Merge(m, src)
}
func (m *MaximumRequest) XXX_Size() int {
	return xxx_messageInfo_MaximumRequest.Size(m)
}
func (m *MaximumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MaximumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MaximumRequest proto.InternalMessageInfo

func (m *MaximumRequest) GetNumber() *Number {
	if m != nil {
		return m.Number
	}
	return nil
}

type MaximumResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaximumResponse) Reset()         { *m = MaximumResponse{} }
func (m *MaximumResponse) String() string { return proto.CompactTextString(m) }
func (*MaximumResponse) ProtoMessage()    {}
func (*MaximumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d531410882a4b8ff, []int{2}
}

func (m *MaximumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaximumResponse.Unmarshal(m, b)
}
func (m *MaximumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaximumResponse.Marshal(b, m, deterministic)
}
func (m *MaximumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaximumResponse.Merge(m, src)
}
func (m *MaximumResponse) XXX_Size() int {
	return xxx_messageInfo_MaximumResponse.Size(m)
}
func (m *MaximumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MaximumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MaximumResponse proto.InternalMessageInfo

func (m *MaximumResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Number)(nil), "maximum.Number")
	proto.RegisterType((*MaximumRequest)(nil), "maximum.MaximumRequest")
	proto.RegisterType((*MaximumResponse)(nil), "maximum.MaximumResponse")
}

func init() {
	proto.RegisterFile("go-grpc-find-maximum/models/maximum.proto", fileDescriptor_d531410882a4b8ff)
}

var fileDescriptor_d531410882a4b8ff = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4c, 0xcf, 0xd7, 0x4d,
	0x2f, 0x2a, 0x48, 0xd6, 0x4d, 0xcb, 0xcc, 0x4b, 0xd1, 0xcd, 0x4d, 0xac, 0xc8, 0xcc, 0x2d, 0xcd,
	0xd5, 0xcf, 0xcd, 0x4f, 0x49, 0xcd, 0x29, 0xd6, 0x87, 0x72, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2,
	0x85, 0xd8, 0xa1, 0x5c, 0x25, 0x05, 0x2e, 0x36, 0xbf, 0xd2, 0xdc, 0xa4, 0xd4, 0x22, 0x21, 0x31,
	0x2e, 0xb6, 0x3c, 0x30, 0x4b, 0x82, 0x51, 0x81, 0x51, 0x83, 0x35, 0x08, 0xca, 0x53, 0xb2, 0xe4,
	0xe2, 0xf3, 0x85, 0x28, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x52, 0x47, 0x51, 0xc9,
	0x6d, 0xc4, 0xaf, 0x07, 0x33, 0x1c, 0x62, 0x14, 0x5c, 0xab, 0x26, 0x17, 0x3f, 0x5c, 0x6b, 0x71,
	0x41, 0x7e, 0x5e, 0x71, 0x2a, 0xc8, 0x96, 0xa2, 0xd4, 0xe2, 0xd2, 0x9c, 0x12, 0x98, 0x2d, 0x10,
	0x9e, 0x51, 0x0c, 0x97, 0x90, 0x5b, 0x66, 0x5e, 0x0a, 0x54, 0x79, 0x70, 0x6a, 0x51, 0x59, 0x66,
	0x72, 0xaa, 0x90, 0x1b, 0x17, 0x37, 0x92, 0xa8, 0x90, 0x38, 0xdc, 0x22, 0x54, 0x17, 0x49, 0x49,
	0x60, 0x4a, 0x40, 0xec, 0x53, 0x62, 0xd0, 0x60, 0x34, 0x60, 0x74, 0xe2, 0x8c, 0x82, 0x79, 0x38,
	0x89, 0x0d, 0x1c, 0x00, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x5c, 0x38, 0xb3, 0x2d,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FindMaximumServiceClient is the client API for FindMaximumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FindMaximumServiceClient interface {
	FindMaximum(ctx context.Context, opts ...grpc.CallOption) (FindMaximumService_FindMaximumClient, error)
}

type findMaximumServiceClient struct {
	cc *grpc.ClientConn
}

func NewFindMaximumServiceClient(cc *grpc.ClientConn) FindMaximumServiceClient {
	return &findMaximumServiceClient{cc}
}

func (c *findMaximumServiceClient) FindMaximum(ctx context.Context, opts ...grpc.CallOption) (FindMaximumService_FindMaximumClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FindMaximumService_serviceDesc.Streams[0], "/maximum.FindMaximumService/FindMaximum", opts...)
	if err != nil {
		return nil, err
	}
	x := &findMaximumServiceFindMaximumClient{stream}
	return x, nil
}

type FindMaximumService_FindMaximumClient interface {
	Send(*MaximumRequest) error
	Recv() (*MaximumResponse, error)
	grpc.ClientStream
}

type findMaximumServiceFindMaximumClient struct {
	grpc.ClientStream
}

func (x *findMaximumServiceFindMaximumClient) Send(m *MaximumRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *findMaximumServiceFindMaximumClient) Recv() (*MaximumResponse, error) {
	m := new(MaximumResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FindMaximumServiceServer is the server API for FindMaximumService service.
type FindMaximumServiceServer interface {
	FindMaximum(FindMaximumService_FindMaximumServer) error
}

// UnimplementedFindMaximumServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFindMaximumServiceServer struct {
}

func (*UnimplementedFindMaximumServiceServer) FindMaximum(srv FindMaximumService_FindMaximumServer) error {
	return status.Errorf(codes.Unimplemented, "method FindMaximum not implemented")
}

func RegisterFindMaximumServiceServer(s *grpc.Server, srv FindMaximumServiceServer) {
	s.RegisterService(&_FindMaximumService_serviceDesc, srv)
}

func _FindMaximumService_FindMaximum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FindMaximumServiceServer).FindMaximum(&findMaximumServiceFindMaximumServer{stream})
}

type FindMaximumService_FindMaximumServer interface {
	Send(*MaximumResponse) error
	Recv() (*MaximumRequest, error)
	grpc.ServerStream
}

type findMaximumServiceFindMaximumServer struct {
	grpc.ServerStream
}

func (x *findMaximumServiceFindMaximumServer) Send(m *MaximumResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *findMaximumServiceFindMaximumServer) Recv() (*MaximumRequest, error) {
	m := new(MaximumRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _FindMaximumService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "maximum.FindMaximumService",
	HandlerType: (*FindMaximumServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FindMaximum",
			Handler:       _FindMaximumService_FindMaximum_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "go-grpc-find-maximum/models/maximum.proto",
}
